from . import attach_menu_bot
from . import update_peer_blocked
from . import payments__payment_form
from . import poll_answer
from . import update_read_stories
from . import update_sent_story_reaction
from . import message_reply_header
from . import dialog_filter_chatlist
from . import star_gift_unique
from . import channel_admin_log_event_action_change_available_reactions
from . import sponsored_message
from . import input_reply_to_story
from . import update_story
from . import input_media_invoice
from . import input_invoice_star_gift
from . import update_channel_pinned_topic
from . import theme
from . import web_page_attribute_story
from . import message_media_giveaway
from . import channels__send_as_peers
from . import update_group_call
from . import update_paid_reaction_privacy
from . import messages__message_reactions_list
from . import message_action_bot_allowed
from . import poll
from . import message_reply_story_header
from . import update_message_poll_vote
from . import secure_file
from . import channel
from . import stars_revenue_status
from . import connected_bot
from . import input_invoice_stars
from . import payments__giveaway_info_results
from . import stats__broadcast_revenue_stats
from . import auto_download_settings
from . import update_message_extended_media
from . import invoice
from . import update_user_name
from . import dialog_filter
from . import channel_full
from . import stats__broadcast_stats
from . import message_action_requested_peer
from . import help__premium_promo
from . import input_invoice_star_gift_transfer
from . import user
from . import user_full
from . import payments__checked_gift_code
from . import reaction_count
from . import global_privacy_settings
from . import story_views
from . import sticker_set
from . import messages__votes_list
from . import message_media_document
from . import bot_info
from . import chat_full
from . import message_reactions
from . import bot_business_connection
from . import message_action_star_gift
from . import input_peer_notify_settings
from . import draft_message
from . import input_media_story
from . import auth__sent_code_type_email_code
from . import stories__all_stories
from . import star_gift_attribute_original_details
from . import input_invoice_star_gift_upgrade
from . import document_attribute_video
from . import file_hash
from . import poll_results
from . import message_peer_reaction
from . import message_media_story
from . import document
from . import config
from . import web_view_result_url
from . import message_action_gift_code
from . import stars_transaction
from . import peer_notify_settings
from . import message_media_giveaway_results
from . import update_stars_balance
from . import encrypted_file
from . import payments__stars_status
from . import chatlists__chatlist_invite
