from .channel import channel_fill_access_hash_calc as channel_all_fill_access_hash_calc
from .channel import input_channel_fill_access_hash_calc as input_channel_all_fill_access_hash_calc
from .user import user_fill_access_hash_calc as user_all_fill_access_hash_calc
from .user import input_user_fill_access_hash_calc as input_user_all_fill_access_hash_calc
from .file import file_fill_access_hash_calc as file_all_fill_access_hash_calc
from .file import file_fill_file_reference_calc as file_all_fill_file_reference_calc
from .wallpaper import wallpaper_fill_access_hash_calc as wallpaper_all_fill_access_hash_calc
from .theme import theme_fill_access_hash_calc as theme_all_fill_access_hash_calc

channel_forbidden_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_133_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_148_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_164_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_166_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_167_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_168_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_186_fill_access_hash_calc = channel_all_fill_access_hash_calc
channel_196_fill_access_hash_calc = channel_all_fill_access_hash_calc
input_channel_fill_access_hash_calc = input_channel_all_fill_access_hash_calc
input_peer_channel_fill_access_hash_calc = input_channel_all_fill_access_hash_calc

user_fill_access_hash_calc = user_all_fill_access_hash_calc
user_133_fill_access_hash_calc = user_all_fill_access_hash_calc
user_145_fill_access_hash_calc = user_all_fill_access_hash_calc
user_148_fill_access_hash_calc = user_all_fill_access_hash_calc
user_160_fill_access_hash_calc = user_all_fill_access_hash_calc
user_166_fill_access_hash_calc = user_all_fill_access_hash_calc
user_167_fill_access_hash_calc = user_all_fill_access_hash_calc
user_185_fill_access_hash_calc = user_all_fill_access_hash_calc
user_196_fill_access_hash_calc = user_all_fill_access_hash_calc

input_user_fill_access_hash_calc = input_user_all_fill_access_hash_calc
input_peer_user_fill_access_hash_calc = input_user_all_fill_access_hash_calc

input_photo_fill_access_hash_calc = file_all_fill_access_hash_calc
photo_fill_access_hash_calc = file_all_fill_access_hash_calc
encrypted_file_fill_access_hash_calc = file_all_fill_access_hash_calc
encrypted_file_133_fill_access_hash_calc = file_all_fill_access_hash_calc
document_fill_access_hash_calc = file_all_fill_access_hash_calc
document_133_fill_access_hash_calc = file_all_fill_access_hash_calc

input_photo_fill_file_reference_calc = file_all_fill_file_reference_calc
photo_fill_file_reference_calc = file_all_fill_file_reference_calc
document_fill_file_reference_calc = file_all_fill_file_reference_calc
document_133_fill_file_reference_calc = file_all_fill_file_reference_calc

wall_paper_fill_access_hash_calc = wallpaper_all_fill_access_hash_calc

theme_fill_access_hash_calc = theme_all_fill_access_hash_calc
theme_133_fill_access_hash_calc = theme_all_fill_access_hash_calc
