from tortoise import migrations
from tortoise.migrations import operations as ops
import piltover.db.models.sentcode
from orjson import loads
from piltover.db.enums import AdminLogEntryAction, BotFatherState, CallDiscardReason, ChannelUpdateType, ChatAdminRights, ChatBannedRights, DialogFolderId, EmojiGroupCategory, EmojiGroupType, FileType, InlineQueryPeer, InlineQueryResultType, MediaType, MessageType, NotifySettingsNotPeerType, PeerType, PrivacyRuleKeyType, SecretUpdateType, StickerSetOfficialType, StickerSetType, StickersBotState, SystemObjectType, TaskIqScheduledState, UpdateType, UserStatus
from piltover.db.models.api_application import application_gen_hash
from piltover.db.models.bot import bot_gen_token
from piltover.db.models.chat_invite import invite_gen_nonce
from piltover.db.models.phone_call import call_gen_access_hash
from piltover.db.models.qr_login import qr_gen_nonce
from piltover.db.models.sentcode import PhoneCodePurpose
from piltover.db.models.srp_session import srp_gen_b, srp_gen_created_at
from piltover.db.models.stickerset import stickerset_gen_access_hash
from piltover.db.models.theme_settings import BaseTheme
from piltover.db.models.user_authorization import auth_gen_hash
from piltover.db.models.user_password import password_gen_salt1, password_gen_salt2
from piltover.db.models.utils import IntFlagFieldInstance
from piltover.db.models.web_authorization import auth_gen_expires_at, auth_gen_hash, auth_gen_password
from tortoise.fields.base import OnDelete
from tortoise.fields.data import JSON_DUMPS
from uuid import uuid4
from tortoise import fields
from tortoise.indexes import Index

class Migration(migrations.Migration):
    initial = True

    operations = [
        ops.CreateModel(
            name='AuthCountry',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('iso2', fields.CharField(unique=True, max_length=8)),
                ('name', fields.CharField(max_length=128)),
                ('hidden', fields.BooleanField(default=False)),
            ],
            options={'table': 'authcountry', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='AuthCountryCode',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('country', fields.ForeignKeyField('models.AuthCountry', source_field='country_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('code', fields.CharField(db_index=True, max_length=4)),
                ('prefixes', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('patterns', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
            ],
            options={'table': 'authcountrycode', 'app': 'models', 'unique_together': (('country', 'code'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='AuthKey',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('auth_key', fields.BinaryField()),
                ('layer', fields.SmallIntField(default=133)),
            ],
            options={'table': 'authkey', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChannelPostInfo',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('views', fields.BigIntField(default=0)),
                ('forwards', fields.BigIntField(default=0)),
            ],
            options={'table': 'channelpostinfo', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Language',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('name', fields.CharField(max_length=64)),
                ('native_name', fields.CharField(max_length=64)),
                ('platform', fields.CharField(max_length=16)),
                ('lang_code', fields.CharField(max_length=8)),
                ('base_lang_code', fields.CharField(null=True, max_length=8)),
                ('plural_lang_code', fields.CharField(max_length=8)),
                ('strings_count', fields.IntField()),
                ('translated_count', fields.IntField()),
                ('official', fields.BooleanField(default=False)),
                ('rtl', fields.BooleanField(default=False)),
                ('beta', fields.BooleanField(default=False)),
                ('version', fields.IntField()),
            ],
            options={'table': 'language', 'app': 'models', 'unique_together': (('platform', 'lang_code'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='LanguageString',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('language', fields.ForeignKeyField('models.Language', source_field='language_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('key', fields.CharField(max_length=128)),
                ('deleted', fields.BooleanField(default=False)),
                ('plural', fields.BooleanField(default=False)),
                ('value', fields.TextField(null=True, unique=False)),
                ('zero_value', fields.TextField(null=True, unique=False)),
                ('one_value', fields.TextField(null=True, unique=False)),
                ('two_value', fields.TextField(null=True, unique=False)),
                ('few_value', fields.TextField(null=True, unique=False)),
                ('many_value', fields.TextField(null=True, unique=False)),
                ('version', fields.IntField()),
            ],
            options={'table': 'languagestring', 'app': 'models', 'unique_together': (('language', 'key'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PeerColorOption',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('hidden', fields.BooleanField(default=False)),
                ('is_profile', fields.BooleanField()),
                ('color1', fields.IntField()),
                ('color2', fields.IntField(null=True)),
                ('color3', fields.IntField(null=True)),
                ('color4', fields.IntField(null=True)),
                ('color5', fields.IntField(null=True)),
                ('color6', fields.IntField(null=True)),
                ('dark_color1', fields.IntField(null=True)),
                ('dark_color2', fields.IntField(null=True)),
                ('dark_color3', fields.IntField(null=True)),
                ('dark_color4', fields.IntField(null=True)),
                ('dark_color5', fields.IntField(null=True)),
                ('dark_color6', fields.IntField(null=True)),
            ],
            options={'table': 'peercoloroption', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Poll',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('closed', fields.BooleanField(default=False)),
                ('quiz', fields.BooleanField(default=False)),
                ('public_voters', fields.BooleanField(default=False)),
                ('multiple_choices', fields.BooleanField(default=False)),
                ('question', fields.CharField(max_length=255)),
                ('question_entities', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('solution', fields.CharField(null=True, max_length=200)),
                ('solution_entities', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('ends_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('version', fields.IntField(default=0)),
            ],
            options={'table': 'poll', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('correct', fields.BooleanField(default=False)),
                ('text', fields.CharField(max_length=100)),
                ('entities', fields.JSONField(encoder=JSON_DUMPS, decoder=loads)),
                ('option', fields.BinaryField()),
                ('poll', fields.ForeignKeyField('models.Poll', source_field='poll_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'pollanswer', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='TempAuthKey',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('auth_key', fields.BinaryField()),
                ('expires_at', fields.BigIntField()),
                ('perm_key', fields.OneToOneField('models.AuthKey', source_field='perm_key_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'tempauthkey', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='User',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('phone_number', fields.CharField(null=True, unique=True, max_length=20)),
                ('first_name', fields.CharField(max_length=128)),
                ('last_name', fields.CharField(null=True, max_length=128)),
                ('lang_code', fields.CharField(default='en', max_length=8)),
                ('about', fields.CharField(null=True, max_length=240)),
                ('ttl_days', fields.IntField(default=365)),
                ('birthday', fields.DateField(null=True)),
                ('bot', fields.BooleanField(default=False)),
                ('system', fields.BooleanField(default=False)),
                ('deleted', fields.BooleanField(default=False)),
                ('accent_color', fields.ForeignKeyField('models.PeerColorOption', source_field='accent_color_id', null=True, db_constraint=True, to_field='id', related_name='accent', on_delete=OnDelete.CASCADE)),
                ('profile_color', fields.ForeignKeyField('models.PeerColorOption', source_field='profile_color_id', null=True, db_constraint=True, to_field='id', related_name='profile', on_delete=OnDelete.CASCADE)),
                ('history_ttl_days', fields.SmallIntField(default=0)),
                ('read_dates_private', fields.BooleanField(default=False)),
                ('version', fields.IntField(default=0)),
            ],
            options={'table': 'user', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ApiApplication',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('hash', fields.CharField(default=application_gen_hash, max_length=32)),
                ('name', fields.CharField(max_length=64)),
                ('short_name', fields.CharField(max_length=32)),
                ('owner', fields.OneToOneField('models.User', source_field='owner_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
            ],
            options={'table': 'apiapplication', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Bot',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('owner', fields.ForeignKeyField('models.User', source_field='owner_id', db_constraint=True, to_field='id', related_name='bot_owner', on_delete=OnDelete.CASCADE)),
                ('bot', fields.OneToOneField('models.User', source_field='bot_id', db_constraint=True, to_field='id', related_name='bot_bot', on_delete=OnDelete.CASCADE)),
                ('token_nonce', fields.CharField(default=bot_gen_token, max_length=36)),
            ],
            options={'table': 'bot', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='BotCommand',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('bot', fields.ForeignKeyField('models.User', source_field='bot_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('name', fields.CharField(max_length=32)),
                ('description', fields.CharField(max_length=240)),
            ],
            options={'table': 'botcommand', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='BotFatherUserState',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('state', fields.IntEnumField(description='', enum_type=BotFatherState, generated=False)),
                ('data', fields.BinaryField(null=True)),
                ('last_access', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'botfatheruserstate', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Contact',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('owner', fields.ForeignKeyField('models.User', source_field='owner_id', db_constraint=True, to_field='id', related_name='contact_owner', on_delete=OnDelete.CASCADE)),
                ('target', fields.ForeignKeyField('models.User', source_field='target_id', null=True, db_constraint=True, to_field='id', related_name='target', on_delete=OnDelete.CASCADE)),
                ('known_phone_number', fields.CharField(null=True, max_length=20)),
                ('phone_number', fields.CharField(null=True, max_length=20)),
                ('first_name', fields.CharField(null=True, max_length=128)),
                ('last_name', fields.CharField(null=True, max_length=128)),
            ],
            options={'table': 'contact', 'app': 'models', 'unique_together': (('owner', 'target'), ('owner', 'phone_number')), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='DiscussionReadState',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('discussion_message_id', fields.BigIntField()),
                ('last_message_id', fields.BigIntField(default=0)),
            ],
            options={'table': 'discussionreadstate', 'app': 'models', 'unique_together': (('user', 'discussion_message_id'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InlineQuery',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', related_name='inline_user', on_delete=OnDelete.CASCADE)),
                ('bot', fields.ForeignKeyField('models.User', source_field='bot_id', db_constraint=True, to_field='id', related_name='inline_bot', on_delete=OnDelete.CASCADE)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('query', fields.CharField(max_length=128)),
                ('offset', fields.CharField(null=True, max_length=64)),
                ('inline_peer', fields.IntEnumField(null=True, description='', enum_type=InlineQueryPeer, generated=False)),
            ],
            options={'table': 'inlinequery', 'app': 'models', 'indexes': [Index(fields=['bot_id', 'query', 'offset'])], 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InlineQueryResult',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('query', fields.OneToOneField('models.InlineQuery', source_field='query_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('next_offset', fields.CharField(null=True, max_length=96)),
                ('cache_time', fields.IntField(default=60)),
                ('cache_until', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('gallery', fields.BooleanField()),
                ('private', fields.BooleanField()),
            ],
            options={'table': 'inlinequeryresult', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PollVote',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('answer', fields.ForeignKeyField('models.PollAnswer', source_field='answer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('hidden', fields.BooleanField(default=False)),
                ('voted_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'pollvote', 'app': 'models', 'unique_together': (('user', 'answer'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Presence',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('status', fields.IntEnumField(default=UserStatus.OFFLINE, description='', enum_type=UserStatus, generated=False)),
                ('last_seen', fields.DatetimeField(auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'presence', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PrivacyRule',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('key', fields.IntEnumField(description='', enum_type=PrivacyRuleKeyType, generated=False)),
                ('allow_all', fields.BooleanField()),
                ('allow_contacts', fields.BooleanField()),
            ],
            options={'table': 'privacyrule', 'app': 'models', 'unique_together': (('user', 'key'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PrivacyRuleException',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('rule', fields.ForeignKeyField('models.PrivacyRule', source_field='rule_id', db_constraint=True, to_field='id', related_name='exceptions', on_delete=OnDelete.CASCADE)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('allow', fields.BooleanField()),
            ],
            options={'table': 'privacyruleexception', 'app': 'models', 'unique_together': (('rule', 'user'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SentCode',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('phone_number', fields.CharField(max_length=20)),
                ('code', fields.IntField(default=piltover.db.models.sentcode.SentCode.gen_phone_code)),
                ('hash', fields.UUIDField(default=uuid4)),
                ('expires_at', fields.BigIntField(default=piltover.db.models.sentcode.SentCode.gen_expires_at)),
                ('used', fields.BooleanField(default=False)),
                ('purpose', fields.IntEnumField(description='', enum_type=PhoneCodePurpose, generated=False)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'sentcode', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='State',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('pts', fields.BigIntField(default=0)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'state', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='StickersBotUserState',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('state', fields.IntEnumField(description='', enum_type=StickersBotState, generated=False)),
                ('data', fields.BinaryField(null=True)),
                ('last_access', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'stickersbotuserstate', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Stickerset',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('title', fields.CharField(max_length=64)),
                ('short_name', fields.CharField(null=True, unique=True, max_length=64)),
                ('access_hash', fields.BigIntField(default=stickerset_gen_access_hash)),
                ('owner', fields.ForeignKeyField('models.User', source_field='owner_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('official', fields.BooleanField(default=False)),
                ('hash', fields.IntField(default=0)),
                ('type', fields.IntEnumField(description='', enum_type=StickerSetType, generated=False)),
                ('official_type', fields.IntEnumField(null=True, description='', enum_type=StickerSetOfficialType, generated=False)),
                ('deleted', fields.BooleanField(default=False)),
                ('emoji', fields.BooleanField(default=False)),
                ('masks', fields.BooleanField(default=False)),
            ],
            options={'table': 'stickerset', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='File',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('physical_id', fields.UUIDField(default=uuid4)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('mime_type', fields.CharField(max_length=200)),
                ('size', fields.BigIntField()),
                ('type', fields.IntEnumField(description='', enum_type=FileType, generated=False)),
                ('constant_access_hash', fields.BigIntField(null=True)),
                ('constant_file_ref', fields.UUIDField(null=True)),
                ('filename', fields.TextField(null=True, unique=False)),
                ('width', fields.IntField(null=True)),
                ('height', fields.IntField(null=True)),
                ('duration', fields.FloatField(null=True)),
                ('supports_streaming', fields.BooleanField(default=False)),
                ('nosound', fields.BooleanField(default=False)),
                ('preload_prefix_size', fields.IntField(null=True)),
                ('title', fields.TextField(null=True, unique=False)),
                ('performer', fields.TextField(null=True, unique=False)),
                ('waveform', fields.BinaryField(null=True)),
                ('photo_sizes', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('photo_stripped', fields.BinaryField(null=True)),
                ('photo_path', fields.BinaryField(null=True)),
                ('stickerset', fields.ForeignKeyField('models.Stickerset', source_field='stickerset_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('sticker_pos', fields.IntField(null=True)),
                ('sticker_alt', fields.CharField(null=True, max_length=32)),
                ('sticker_is_mask', fields.BooleanField(default=False)),
                ('sticker_mask_coords', fields.CharField(null=True, max_length=36)),
            ],
            options={'table': 'file', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='BotInfo',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('description', fields.CharField(null=True, max_length=128)),
                ('description_photo', fields.ForeignKeyField('models.File', source_field='description_photo_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('privacy_policy_url', fields.CharField(null=True, max_length=240)),
                ('version', fields.IntField(default=1)),
            ],
            options={'table': 'botinfo', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Chat',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('name', fields.CharField(max_length=64)),
                ('description', fields.CharField(default='', max_length=255)),
                ('version', fields.BigIntField(default=1)),
                ('creator', fields.ForeignKeyField('models.User', source_field='creator_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('photo', fields.ForeignKeyField('models.File', source_field='photo_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('no_forwards', fields.BooleanField(default=False)),
                ('banned_rights', IntFlagFieldInstance(default=ChatBannedRights.NONE, description='VIEW_MESSAGES: 1\nSEND_MESSAGES: 2\nSEND_MEDIA: 4\nSEND_STICKERS: 8\nSEND_GIFS: 16\nSEND_GAMES: 32\nSEND_INLINE: 64\nEMBED_LINKS: 128\nSEND_POLLS: 256\nCHANGE_INFO: 1024\nINVITE_USERS: 32768\nPIN_MESSAGES: 131072\nMANAGE_TOPICS: 262144\nSEND_PHOTOS: 524288\nSEND_VIDEOS: 1048576\nSEND_ROUNDVIDEOS: 2097152\nSEND_AUDIOS: 4194304\nSEND_VOICES: 8388608\nSEND_DOCS: 16777216\nSEND_PLAIN: 33554432', enum_type=ChatBannedRights)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('ttl_period_days', fields.SmallIntField(default=0)),
                ('migrated', fields.BooleanField(default=False)),
                ('participants_count', fields.SmallIntField()),
            ],
            options={'table': 'chat', 'app': 'models', 'pk_attr': 'id'},
            bases=['ChatBase'],
        ),
        ops.CreateModel(
            name='Channel',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('name', fields.CharField(max_length=64)),
                ('description', fields.CharField(default='', max_length=255)),
                ('version', fields.BigIntField(default=1)),
                ('creator', fields.ForeignKeyField('models.User', source_field='creator_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('photo', fields.ForeignKeyField('models.File', source_field='photo_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('no_forwards', fields.BooleanField(default=False)),
                ('banned_rights', IntFlagFieldInstance(default=ChatBannedRights.NONE, description='VIEW_MESSAGES: 1\nSEND_MESSAGES: 2\nSEND_MEDIA: 4\nSEND_STICKERS: 8\nSEND_GIFS: 16\nSEND_GAMES: 32\nSEND_INLINE: 64\nEMBED_LINKS: 128\nSEND_POLLS: 256\nCHANGE_INFO: 1024\nINVITE_USERS: 32768\nPIN_MESSAGES: 131072\nMANAGE_TOPICS: 262144\nSEND_PHOTOS: 524288\nSEND_VIDEOS: 1048576\nSEND_ROUNDVIDEOS: 2097152\nSEND_AUDIOS: 4194304\nSEND_VOICES: 8388608\nSEND_DOCS: 16777216\nSEND_PLAIN: 33554432', enum_type=ChatBannedRights)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('ttl_period_days', fields.SmallIntField(default=0)),
                ('channel', fields.BooleanField(default=False)),
                ('supergroup', fields.BooleanField(default=False)),
                ('pts', fields.BigIntField(default=1)),
                ('signatures', fields.BooleanField(default=False)),
                ('accent_color', fields.ForeignKeyField('models.PeerColorOption', source_field='accent_color_id', null=True, db_constraint=True, to_field='id', related_name='channel_accent', on_delete=OnDelete.SET_NULL)),
                ('profile_color', fields.ForeignKeyField('models.PeerColorOption', source_field='profile_color_id', null=True, db_constraint=True, to_field='id', related_name='channel_profile', on_delete=OnDelete.SET_NULL)),
                ('all_reactions', fields.BooleanField(default=True)),
                ('all_reactions_custom', fields.BooleanField(default=False)),
                ('deleted', fields.BooleanField(default=False)),
                ('nojoin_allow_view', fields.BooleanField(default=False)),
                ('hidden_prehistory', fields.BooleanField(default=False)),
                ('min_available_id', fields.BigIntField(null=True)),
                ('min_available_id_force', fields.BigIntField(null=True)),
                ('migrated_from', fields.OneToOneField('models.Chat', source_field='migrated_from_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('join_to_send', fields.BooleanField(default=True)),
                ('join_request', fields.BooleanField(default=False)),
                ('discussion', fields.ForeignKeyField('models.Channel', source_field='discussion_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('is_discussion', fields.BooleanField(default=False)),
                ('accent_emoji', fields.ForeignKeyField('models.File', source_field='accent_emoji_id', null=True, db_constraint=True, to_field='id', related_name='channel_accent_emoji', on_delete=OnDelete.SET_NULL)),
                ('profile_emoji', fields.ForeignKeyField('models.File', source_field='profile_emoji_id', null=True, db_constraint=True, to_field='id', related_name='channel_profile_emoji', on_delete=OnDelete.SET_NULL)),
                ('slowmode_seconds', fields.IntField(null=True)),
                ('participants_hidden', fields.BooleanField(default=False)),
            ],
            options={'table': 'channel', 'app': 'models', 'pk_attr': 'id'},
            bases=['ChatBase'],
        ),
        ops.CreateModel(
            name='AdminLogEntry',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('action', fields.IntEnumField(description='', enum_type=AdminLogEntryAction, generated=False)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('prev', fields.BinaryField(null=True)),
                ('old_photo', fields.ForeignKeyField('models.File', source_field='old_photo_id', null=True, db_constraint=True, to_field='id', related_name='old_photo', on_delete=OnDelete.CASCADE)),
                ('old_banned_rights', IntFlagFieldInstance(null=True, description='VIEW_MESSAGES: 1\nSEND_MESSAGES: 2\nSEND_MEDIA: 4\nSEND_STICKERS: 8\nSEND_GIFS: 16\nSEND_GAMES: 32\nSEND_INLINE: 64\nEMBED_LINKS: 128\nSEND_POLLS: 256\nCHANGE_INFO: 1024\nINVITE_USERS: 32768\nPIN_MESSAGES: 131072\nMANAGE_TOPICS: 262144\nSEND_PHOTOS: 524288\nSEND_VIDEOS: 1048576\nSEND_ROUNDVIDEOS: 2097152\nSEND_AUDIOS: 4194304\nSEND_VOICES: 8388608\nSEND_DOCS: 16777216\nSEND_PLAIN: 33554432', enum_type=ChatBannedRights)),
                ('old_channel', fields.ForeignKeyField('models.Channel', source_field='old_channel_id', null=True, db_constraint=True, to_field='id', related_name='old_channel', on_delete=OnDelete.CASCADE)),
                ('new', fields.BinaryField(null=True)),
                ('new_photo', fields.ForeignKeyField('models.File', source_field='new_photo_id', null=True, db_constraint=True, to_field='id', related_name='new_photo', on_delete=OnDelete.CASCADE)),
                ('new_banned_rights', IntFlagFieldInstance(null=True, description='VIEW_MESSAGES: 1\nSEND_MESSAGES: 2\nSEND_MEDIA: 4\nSEND_STICKERS: 8\nSEND_GIFS: 16\nSEND_GAMES: 32\nSEND_INLINE: 64\nEMBED_LINKS: 128\nSEND_POLLS: 256\nCHANGE_INFO: 1024\nINVITE_USERS: 32768\nPIN_MESSAGES: 131072\nMANAGE_TOPICS: 262144\nSEND_PHOTOS: 524288\nSEND_VIDEOS: 1048576\nSEND_ROUNDVIDEOS: 2097152\nSEND_AUDIOS: 4194304\nSEND_VOICES: 8388608\nSEND_DOCS: 16777216\nSEND_PLAIN: 33554432', enum_type=ChatBannedRights)),
                ('new_channel', fields.ForeignKeyField('models.Channel', source_field='new_channel_id', null=True, db_constraint=True, to_field='id', related_name='new_channel', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'adminlogentry', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChannelUpdate',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('type', fields.IntEnumField(description='', enum_type=ChannelUpdateType, generated=False)),
                ('pts', fields.BigIntField()),
                ('pts_count', fields.IntField(default=0)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('related_id', fields.BigIntField(null=True, db_index=True)),
                ('extra_data', fields.BinaryField(null=True)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'channelupdate', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChatInvite',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('revoked', fields.BooleanField(default=False)),
                ('expires_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('request_needed', fields.BooleanField(default=False)),
                ('nonce', fields.CharField(default=invite_gen_nonce, max_length=16)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.Chat', source_field='chat_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('updated_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('usage_limit', fields.IntField(null=True)),
                ('usage', fields.IntField(default=0)),
                ('title', fields.CharField(null=True, max_length=128)),
            ],
            options={'table': 'chatinvite', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChatInviteRequest',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('invite', fields.ForeignKeyField('models.ChatInvite', source_field='invite_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'chatinviterequest', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.Chat', source_field='chat_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat_channel_id', fields.BigIntField(db_index=True)),
                ('inviter_id', fields.BigIntField(default=0)),
                ('invited_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('banned_until', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('banned_rights', IntFlagFieldInstance(default=ChatBannedRights.NONE, description='VIEW_MESSAGES: 1\nSEND_MESSAGES: 2\nSEND_MEDIA: 4\nSEND_STICKERS: 8\nSEND_GIFS: 16\nSEND_GAMES: 32\nSEND_INLINE: 64\nEMBED_LINKS: 128\nSEND_POLLS: 256\nCHANGE_INFO: 1024\nINVITE_USERS: 32768\nPIN_MESSAGES: 131072\nMANAGE_TOPICS: 262144\nSEND_PHOTOS: 524288\nSEND_VIDEOS: 1048576\nSEND_ROUNDVIDEOS: 2097152\nSEND_AUDIOS: 4194304\nSEND_VOICES: 8388608\nSEND_DOCS: 16777216\nSEND_PLAIN: 33554432', enum_type=ChatBannedRights)),
                ('admin_rights', IntFlagFieldInstance(default=ChatAdminRights.NONE, description='CHANGE_INFO: 1\nPOST_MESSAGES: 2\nEDIT_MESSAGES: 4\nDELETE_MESSAGES: 8\nBAN_USERS: 16\nINVITE_USERS: 32\nPIN_MESSAGES: 128\nADD_ADMINS: 512\nANONYMOUS: 1024\nMANAGE_CALL: 2048\nOTHER: 4096\nMANAGE_TOPICS: 8192\nPOST_STORIES: 16384\nEDIT_STORIES: 32768\nDELETE_STORIES: 65536', enum_type=ChatAdminRights)),
                ('invite', fields.ForeignKeyField('models.ChatInvite', source_field='invite_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('admin_rank', fields.CharField(default='', max_length=24)),
                ('promoted_by_id', fields.BigIntField(default=0)),
                ('min_message_id', fields.BigIntField(null=True)),
                ('left', fields.BooleanField(default=False)),
            ],
            options={'table': 'chatparticipant', 'app': 'models', 'unique_together': (('user', 'chat'), ('user', 'channel')), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='EmojiGroup',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('category', fields.IntEnumField(db_index=True, description='', enum_type=EmojiGroupCategory, generated=False)),
                ('type', fields.IntEnumField(description='', enum_type=EmojiGroupType, generated=False)),
                ('position', fields.SmallIntField()),
                ('name', fields.CharField(max_length=64)),
                ('icon_emoji', fields.ForeignKeyField('models.File', source_field='icon_emoji_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('emoticons', fields.BinaryField(null=True)),
            ],
            options={'table': 'emojigroup', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('file', fields.ForeignKeyField('models.File', source_field='file_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('key_fingerprint', fields.BigIntField()),
            ],
            options={'table': 'encryptedfile', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='FavedSticker',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('sticker', fields.ForeignKeyField('models.File', source_field='sticker_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('faved_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'favedsticker', 'app': 'models', 'unique_together': (('user', 'sticker'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='GifBotFile',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('tenor_id', fields.CharField(unique=True, max_length=32)),
                ('file', fields.ForeignKeyField('models.File', source_field='file_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'gifbotfile', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InlineQueryResultItem',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('result', fields.ForeignKeyField('models.InlineQueryResult', source_field='result_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('item_id', fields.CharField(max_length=64)),
                ('position', fields.SmallIntField()),
                ('type', fields.CharEnumField(description='PHOTO: photo\nSTICKER: sticker\nGIF: gif\nVOICE: voice\nVENUE: venue\nVIDEO: video\nCONTACT: contact\nAUDIO: audio\nLOCATION: location\nARTICLE: article\nFILE: file', enum_type=InlineQueryResultType, max_length=8)),
                ('photo', fields.ForeignKeyField('models.File', source_field='photo_id', null=True, db_constraint=True, to_field='id', related_name='inline_photo', on_delete=OnDelete.CASCADE)),
                ('document', fields.ForeignKeyField('models.File', source_field='document_id', null=True, db_constraint=True, to_field='id', related_name='inline_document', on_delete=OnDelete.CASCADE)),
                ('title', fields.CharField(null=True, max_length=128)),
                ('description', fields.CharField(null=True, max_length=240)),
                ('url', fields.TextField(null=True, unique=False)),
                ('send_message_text', fields.TextField(null=True, unique=False)),
                ('send_message_no_webpage', fields.BooleanField(default=False)),
                ('send_message_invert_media', fields.BooleanField(default=False)),
                ('send_message_entities', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
            ],
            options={'table': 'inlinequeryresultitem', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InstalledStickerset',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('set', fields.ForeignKeyField('models.Stickerset', source_field='set_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('installed_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('archived', fields.BooleanField(default=False)),
                ('pos', fields.IntField(default=0)),
            ],
            options={'table': 'installedstickerset', 'app': 'models', 'unique_together': (('set', 'user'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageComments',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('discussion_channel', fields.ForeignKeyField('models.Channel', source_field='discussion_channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('discussion_pts', fields.BigIntField()),
            ],
            options={'table': 'messagecomments', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('spoiler', fields.BooleanField(default=False)),
                ('type', fields.IntEnumField(default=MediaType.DOCUMENT, description='', enum_type=MediaType, generated=False)),
                ('file', fields.ForeignKeyField('models.File', source_field='file_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('poll', fields.ForeignKeyField('models.Poll', source_field='poll_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('static_data', fields.BinaryField(null=True)),
            ],
            options={'table': 'messagemedia', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Peer',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('owner', fields.ForeignKeyField('models.User', source_field='owner_id', null=True, db_constraint=True, to_field='id', related_name='owner', on_delete=OnDelete.CASCADE)),
                ('type', fields.IntEnumField(description='', enum_type=PeerType, generated=False)),
                ('blocked_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('user_ttl_period_days', fields.SmallIntField(null=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', related_name='user', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.Chat', source_field='chat_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'peer', 'app': 'models', 'unique_together': (('owner', 'user'), ('owner', 'chat'), ('owner', 'channel')), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Dialog',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('pinned_index', fields.SmallIntField(null=True)),
                ('unread_mark', fields.BooleanField(default=False)),
                ('folder_id', fields.IntEnumField(default=DialogFolderId.ALL, description='', enum_type=DialogFolderId, generated=False)),
                ('visible', fields.BooleanField(default=True)),
                ('peer', fields.OneToOneField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'dialog', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='DialogFolder',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('id_for_user', fields.SmallIntField()),
                ('name', fields.CharField(max_length=16)),
                ('owner', fields.ForeignKeyField('models.User', source_field='owner_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('position', fields.SmallIntField(default=0)),
                ('contacts', fields.BooleanField(default=False)),
                ('non_contacts', fields.BooleanField(default=False)),
                ('groups', fields.BooleanField(default=False)),
                ('broadcasts', fields.BooleanField(default=False)),
                ('bots', fields.BooleanField(default=False)),
                ('exclude_muted', fields.BooleanField(default=False)),
                ('exclude_read', fields.BooleanField(default=False)),
                ('exclude_archived', fields.BooleanField(default=False)),
                ('pinned_peers', fields.ManyToManyField('models.Peer', unique=True, db_constraint=True, through='dialogfolder_peer_pinned', forward_key='peer_id', backward_key='dialogfolder_id', related_name='pinned_peers', on_delete=OnDelete.CASCADE)),
                ('include_peers', fields.ManyToManyField('models.Peer', unique=True, db_constraint=True, through='dialogfolder_peer_include', forward_key='peer_id', backward_key='dialogfolder_id', related_name='include_peers', on_delete=OnDelete.CASCADE)),
                ('exclude_peers', fields.ManyToManyField('models.Peer', unique=True, db_constraint=True, through='dialogfolder_peer_exclude', forward_key='peer_id', backward_key='dialogfolder_id', related_name='exclude_peers', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'dialogfolder', 'app': 'models', 'unique_together': (('owner', 'id_for_user'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageFwdHeader',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('from_user', fields.ForeignKeyField('models.User', source_field='from_user_id', null=True, db_constraint=True, to_field='id', related_name='from_user', on_delete=OnDelete.CASCADE)),
                ('from_chat', fields.ForeignKeyField('models.Chat', source_field='from_chat_id', null=True, db_constraint=True, to_field='id', related_name='from_chat', on_delete=OnDelete.CASCADE)),
                ('from_channel', fields.ForeignKeyField('models.Channel', source_field='from_channel_id', null=True, db_constraint=True, to_field='id', related_name='from_channel', on_delete=OnDelete.CASCADE)),
                ('from_name', fields.CharField(max_length=64)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=False)),
                ('saved_out', fields.BooleanField()),
                ('channel_post_id', fields.BigIntField(null=True)),
                ('channel_post_author', fields.CharField(null=True, max_length=128)),
                ('saved_peer', fields.ForeignKeyField('models.Peer', source_field='saved_peer_id', null=True, db_constraint=True, to_field='id', related_name='saved_peer', on_delete=OnDelete.CASCADE)),
                ('saved_id', fields.BigIntField(null=True)),
                ('saved_from', fields.ForeignKeyField('models.User', source_field='saved_from_id', null=True, db_constraint=True, to_field='id', related_name='saved_user', on_delete=OnDelete.CASCADE)),
                ('saved_name', fields.CharField(null=True, max_length=64)),
                ('saved_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'messagefwdheader', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageContent',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('message', fields.TextField(null=True, unique=False)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('edit_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('type', fields.IntEnumField(default=MessageType.REGULAR, description='', enum_type=MessageType, generated=False)),
                ('entities', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('extra_info', fields.BinaryField(null=True)),
                ('media_group_id', fields.BigIntField(null=True)),
                ('channel_post', fields.BooleanField(default=False)),
                ('post_author', fields.CharField(null=True, max_length=128)),
                ('scheduled_date', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('ttl_period_days', fields.SmallIntField(null=True)),
                ('reply_markup', fields.BinaryField(null=True)),
                ('no_forwards', fields.BooleanField(default=False)),
                ('edit_hide', fields.BooleanField(default=False)),
                ('author', fields.ForeignKeyField('models.User', source_field='author_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('media', fields.ForeignKeyField('models.MessageMedia', source_field='media_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('fwd_header', fields.ForeignKeyField('models.MessageFwdHeader', source_field='fwd_header_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('post_info', fields.ForeignKeyField('models.ChannelPostInfo', source_field='post_info_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('via_bot', fields.ForeignKeyField('models.User', source_field='via_bot_id', null=True, db_constraint=True, to_field='id', related_name='msg_via_bot', on_delete=OnDelete.SET_NULL)),
                ('discussion', fields.ForeignKeyField('models.MessageContent', source_field='discussion_id', null=True, db_constraint=True, to_field='id', related_name='msg_discussion_message', on_delete=OnDelete.SET_NULL)),
                ('comments_info', fields.ForeignKeyField('models.MessageComments', source_field='comments_info_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('is_discussion', fields.BooleanField(default=False)),
                ('version', fields.IntField(default=0)),
                ('reactions_version', fields.IntField(default=0)),
            ],
            options={'table': 'messagecontent', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageMention',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.Chat', source_field='chat_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('message', fields.ForeignKeyField('models.MessageContent', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('read', fields.BooleanField(default=False)),
            ],
            options={'table': 'messagemention', 'app': 'models', 'unique_together': (('user', 'message'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageRef',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('content', fields.ForeignKeyField('models.MessageContent', source_field='content_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('peer', fields.ForeignKeyField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('random_id', fields.BigIntField(null=True)),
                ('pinned', fields.BooleanField(default=False)),
                ('version', fields.IntField(default=0)),
                ('from_scheduled', fields.BooleanField(default=False)),
                ('reply_to', fields.ForeignKeyField('models.MessageRef', source_field='reply_to_id', null=True, db_constraint=True, to_field='id', related_name='reply', on_delete=OnDelete.SET_NULL)),
                ('top_message', fields.ForeignKeyField('models.MessageRef', source_field='top_message_id', null=True, db_constraint=True, to_field='id', related_name='msg_top_message', on_delete=OnDelete.SET_NULL)),
            ],
            options={'table': 'messageref', 'app': 'models', 'unique_together': (('peer', 'content'), ('peer', 'random_id')), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='CallbackQuery',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('message', fields.ForeignKeyField('models.MessageRef', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('data', fields.BinaryField()),
            ],
            options={'table': 'callbackquery', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageDraft',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('message', fields.TextField(unique=False)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('peer', fields.OneToOneField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('reply_to', fields.ForeignKeyField('models.MessageRef', source_field='reply_to_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.SET_NULL)),
                ('no_webpage', fields.BooleanField(default=False)),
                ('invert_media', fields.BooleanField(default=False)),
                ('entities', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
            ],
            options={'table': 'messagedraft', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageMediaRead',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('message', fields.ForeignKeyField('models.MessageRef', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'messagemediaread', 'app': 'models', 'unique_together': (('user', 'message'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageRelated',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('message', fields.ForeignKeyField('models.MessageContent', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.Chat', source_field='chat_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'messagerelated', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PeerNotifySettings',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('peer', fields.ForeignKeyField('models.Peer', source_field='peer_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('not_peer', fields.IntEnumField(null=True, description='', enum_type=NotifySettingsNotPeerType, generated=False)),
                ('show_previews', fields.BooleanField(default=True)),
                ('muted', fields.BooleanField(default=False)),
                ('muted_until', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'peernotifysettings', 'app': 'models', 'unique_together': (('user', 'peer'), ('user', 'not_peer')), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Reaction',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('reaction_id', fields.UUIDField(db_index=True)),
                ('reaction', fields.CharField(max_length=8)),
                ('title', fields.CharField(max_length=64)),
                ('static_icon', fields.ForeignKeyField('models.File', source_field='static_icon_id', db_constraint=True, to_field='id', related_name='static_icon', on_delete=OnDelete.CASCADE)),
                ('appear_animation', fields.ForeignKeyField('models.File', source_field='appear_animation_id', db_constraint=True, to_field='id', related_name='appear_animation', on_delete=OnDelete.CASCADE)),
                ('select_animation', fields.ForeignKeyField('models.File', source_field='select_animation_id', db_constraint=True, to_field='id', related_name='select_animation', on_delete=OnDelete.CASCADE)),
                ('activate_animation', fields.ForeignKeyField('models.File', source_field='activate_animation_id', db_constraint=True, to_field='id', related_name='activate_animation', on_delete=OnDelete.CASCADE)),
                ('effect_animation', fields.ForeignKeyField('models.File', source_field='effect_animation_id', db_constraint=True, to_field='id', related_name='effect_animation', on_delete=OnDelete.CASCADE)),
                ('around_animation', fields.ForeignKeyField('models.File', source_field='around_animation_id', null=True, db_constraint=True, to_field='id', related_name='around_animation', on_delete=OnDelete.CASCADE)),
                ('center_icon', fields.ForeignKeyField('models.File', source_field='center_icon_id', null=True, db_constraint=True, to_field='id', related_name='center_icon', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'reaction', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='AvailableChannelReaction',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('reaction', fields.ForeignKeyField('models.Reaction', source_field='reaction_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'availablechannelreaction', 'app': 'models', 'unique_together': (('channel', 'reaction'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('message', fields.ForeignKeyField('models.MessageContent', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('reaction', fields.ForeignKeyField('models.Reaction', source_field='reaction_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('custom_emoji', fields.ForeignKeyField('models.File', source_field='custom_emoji_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'messagereaction', 'app': 'models', 'unique_together': (('user', 'message'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ReadHistoryChunk',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('peer', fields.ForeignKeyField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('read_content_id', fields.BigIntField()),
                ('read_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'readhistorychunk', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ReadState',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('last_message_id', fields.BigIntField(default=0)),
                ('last_reaction_id', fields.BigIntField(default=0)),
                ('peer', fields.OneToOneField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'readstate', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='RecentReaction',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('reaction', fields.ForeignKeyField('models.Reaction', source_field='reaction_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('used_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'recentreaction', 'app': 'models', 'unique_together': (('user', 'reaction'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='RecentSticker',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('sticker', fields.ForeignKeyField('models.File', source_field='sticker_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('used_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'recentsticker', 'app': 'models', 'unique_together': (('user', 'sticker'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SavedDialog',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('pinned_index', fields.SmallIntField(null=True)),
                ('peer', fields.OneToOneField('models.Peer', source_field='peer_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'saveddialog', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SavedGif',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('gif', fields.ForeignKeyField('models.File', source_field='gif_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('last_access', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'savedgif', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SlowmodeLastMessage',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('channel', fields.ForeignKeyField('models.Channel', source_field='channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('last_message', fields.DatetimeField(auto_now=False, auto_now_add=False)),
            ],
            options={'table': 'slowmodelastmessage', 'app': 'models', 'unique_together': (('channel', 'user'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='StickersetThumb',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('set', fields.ForeignKeyField('models.Stickerset', source_field='set_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('file', fields.ForeignKeyField('models.File', source_field='file_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'stickersetthumb', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SystemObjectId',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('type', fields.IntEnumField(description='', enum_type=SystemObjectType, generated=False)),
                ('original_id', fields.BigIntField()),
                ('checksum', fields.BigIntField()),
                ('our_file', fields.ForeignKeyField('models.File', source_field='our_file_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('our_stickerset', fields.ForeignKeyField('models.Stickerset', source_field='our_stickerset_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('our_emoji_group', fields.ForeignKeyField('models.EmojiGroup', source_field='our_emoji_group_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'systemobjectid', 'app': 'models', 'unique_together': (('type', 'original_id'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='TaskIqScheduledDeleteMessage',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('scheduled_for', fields.BigIntField(db_index=True)),
                ('start_processing', fields.BigIntField(null=True)),
                ('message', fields.OneToOneField('models.MessageContent', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'taskiqscheduleddeletemessage', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='TaskIqScheduledDeleteUser',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('state', fields.IntEnumField(default=TaskIqScheduledState.SCHEDULED, description='', enum_type=TaskIqScheduledState, generated=False)),
                ('scheduled_time', fields.DatetimeField(db_index=True, auto_now=False, auto_now_add=False)),
                ('state_updated_at', fields.BigIntField(db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'taskiqscheduleddeleteuser', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='TaskIqScheduledMessage',
            fields=[
                ('id', fields.UUIDField(primary_key=True, default=uuid4, unique=True, db_index=True)),
                ('state', fields.IntEnumField(default=TaskIqScheduledState.SCHEDULED, description='', enum_type=TaskIqScheduledState, generated=False)),
                ('scheduled_time', fields.BigIntField(db_index=True)),
                ('state_updated_at', fields.BigIntField(db_index=True)),
                ('message', fields.OneToOneField('models.MessageRef', source_field='message_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('mentioned_users', fields.BinaryField(null=True)),
                ('opposite', fields.BooleanField()),
            ],
            options={'table': 'taskiqscheduledmessage', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Theme',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('creator', fields.ForeignKeyField('models.User', source_field='creator_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('title', fields.CharField(max_length=128)),
                ('slug', fields.CharField(unique=True, max_length=64)),
                ('for_chat', fields.BooleanField(default=False)),
                ('emoticon', fields.CharField(null=True, max_length=8)),
                ('document', fields.ForeignKeyField('models.File', source_field='document_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'theme', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Update',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('update_type', fields.IntEnumField(description='', enum_type=UpdateType, generated=False)),
                ('pts', fields.BigIntField()),
                ('pts_count', fields.IntField(default=0)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('related_id', fields.BigIntField(null=True, db_index=True)),
                ('related_ids', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('additional_data', fields.JSONField(null=True, encoder=JSON_DUMPS, decoder=loads)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'update', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UploadingFile',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('file_id', fields.CharField(db_index=True, max_length=64)),
                ('physical_id', fields.UUIDField(default=uuid4)),
                ('total_parts', fields.IntField(default=0)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('mime', fields.CharField(null=True, max_length=64)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'uploadingfile', 'app': 'models', 'unique_together': (('user', 'file_id'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UploadingFilePart',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('part_id', fields.IntField()),
                ('physical_id', fields.UUIDField(default=uuid4)),
                ('size', fields.IntField()),
                ('file', fields.ForeignKeyField('models.UploadingFile', source_field='file_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'uploadingfilepart', 'app': 'models', 'unique_together': (('file', 'part_id'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('hash', fields.CharField(default=auth_gen_hash, db_index=True, max_length=32)),
                ('ip', fields.CharField(max_length=64)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('active_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('mfa_pending', fields.BooleanField(default=False)),
                ('allow_encrypted_requests', fields.BooleanField(default=True)),
                ('allow_call_requests', fields.BooleanField(default=True)),
                ('confirmed', fields.BooleanField(default=False)),
                ('platform', fields.CharField(default='Unknown', max_length=128)),
                ('device_model', fields.CharField(default='Unknown', max_length=128)),
                ('system_version', fields.CharField(default='Unknown', max_length=32)),
                ('app_version', fields.CharField(default='Unknown', max_length=32)),
                ('upd_seq', fields.BigIntField(default=0)),
                ('upd_qts', fields.BigIntField(default=0)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('key', fields.OneToOneField('models.AuthKey', source_field='key_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'userauthorization', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='EncryptedChat',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('access_hash', fields.BigIntField(default=825666558780444090)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('from_user', fields.ForeignKeyField('models.User', source_field='from_user_id', db_constraint=True, to_field='id', related_name='enc_from_user', on_delete=OnDelete.CASCADE)),
                ('from_sess', fields.ForeignKeyField('models.UserAuthorization', source_field='from_sess_id', db_constraint=True, to_field='id', related_name='enc_from_sess', on_delete=OnDelete.CASCADE)),
                ('to_user', fields.ForeignKeyField('models.User', source_field='to_user_id', db_constraint=True, to_field='id', related_name='enc_to_user', on_delete=OnDelete.CASCADE)),
                ('to_sess', fields.ForeignKeyField('models.UserAuthorization', source_field='to_sess_id', null=True, db_constraint=True, to_field='id', related_name='enc_to_sess', on_delete=OnDelete.CASCADE)),
                ('dh_version', fields.IntField()),
                ('g_a', fields.BinaryField()),
                ('g_b', fields.BinaryField()),
                ('key_fp', fields.BigIntField(null=True)),
                ('discarded', fields.BooleanField(default=False)),
                ('history_deleted', fields.BooleanField(default=False)),
            ],
            options={'table': 'encryptedchat', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('access_hash', fields.BigIntField(default=call_gen_access_hash)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('started_at', fields.DatetimeField(null=True, auto_now=False, auto_now_add=False)),
                ('from_user', fields.ForeignKeyField('models.User', source_field='from_user_id', db_constraint=True, to_field='id', related_name='call_from_user', on_delete=OnDelete.CASCADE)),
                ('from_sess', fields.ForeignKeyField('models.UserAuthorization', source_field='from_sess_id', db_constraint=True, to_field='id', related_name='call_from_sess', on_delete=OnDelete.CASCADE)),
                ('to_user', fields.ForeignKeyField('models.User', source_field='to_user_id', db_constraint=True, to_field='id', related_name='call_to_user', on_delete=OnDelete.CASCADE)),
                ('to_sess', fields.ForeignKeyField('models.UserAuthorization', source_field='to_sess_id', null=True, db_constraint=True, to_field='id', related_name='call_to_sess', on_delete=OnDelete.CASCADE)),
                ('g_a_hash', fields.BinaryField()),
                ('g_a', fields.BinaryField(null=True)),
                ('g_b', fields.BinaryField(null=True)),
                ('key_fp', fields.BigIntField(null=True)),
                ('discard_reason', fields.IntEnumField(null=True, description='', enum_type=CallDiscardReason, generated=False)),
                ('duration', fields.IntField(null=True)),
                ('protocol', fields.BinaryField()),
            ],
            options={'table': 'phonecall', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='QrLogin',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('created_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('key', fields.ForeignKeyField('models.AuthKey', source_field='key_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('nonce', fields.BigIntField(default=qr_gen_nonce)),
                ('auth', fields.ForeignKeyField('models.UserAuthorization', source_field='auth_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'qrlogin', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SecretUpdate',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('qts', fields.BigIntField()),
                ('type', fields.IntEnumField(description='', enum_type=SecretUpdateType, generated=False)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
                ('authorization', fields.ForeignKeyField('models.UserAuthorization', source_field='authorization_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('chat', fields.ForeignKeyField('models.EncryptedChat', source_field='chat_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('data', fields.BinaryField(null=True)),
                ('message_random_id', fields.BigIntField(null=True)),
                ('message_is_service', fields.BooleanField(null=True)),
                ('message_file', fields.ForeignKeyField('models.EncryptedFile', source_field='message_file_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'secretupdate', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserBackgroundEmojis',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('accent_emoji', fields.ForeignKeyField('models.File', source_field='accent_emoji_id', null=True, db_constraint=True, to_field='id', related_name='accent_emoji', on_delete=OnDelete.CASCADE)),
                ('profile_emoji', fields.ForeignKeyField('models.File', source_field='profile_emoji_id', null=True, db_constraint=True, to_field='id', related_name='profile_emoji', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'userbackgroundemojis', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserPassword',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('salt1', fields.BinaryField(default=password_gen_salt1)),
                ('salt2', fields.BinaryField(default=password_gen_salt2)),
                ('password', fields.BinaryField(null=True)),
                ('hint', fields.CharField(null=True, max_length=120)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('modified_at', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'userpassword', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='SrpSession',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('priv_b', fields.BinaryField(default=srp_gen_b)),
                ('created_at', fields.BigIntField(default=srp_gen_created_at)),
                ('password', fields.ForeignKeyField('models.UserPassword', source_field='password_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'srpsession', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserPasswordReset',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('date', fields.DatetimeField(auto_now=False, auto_now_add=True)),
            ],
            options={'table': 'userpasswordreset', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserPersonalChannel',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.OneToOneField('models.Channel', source_field='channel_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'userpersonalchannel', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('current', fields.BooleanField(default=False)),
                ('fallback', fields.BooleanField(default=False)),
                ('file', fields.ForeignKeyField('models.File', source_field='file_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'userphoto', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='UserReactionsSettings',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('default_reaction', fields.ForeignKeyField('models.Reaction', source_field='default_reaction_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'userreactionssettings', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Username',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('username', fields.CharField(unique=True, max_length=64)),
                ('user', fields.OneToOneField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('channel', fields.OneToOneField('models.Channel', source_field='channel_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'username', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='WallpaperSettings',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('blur', fields.BooleanField(default=False)),
                ('motion', fields.BooleanField(default=False)),
                ('background_color', fields.IntField(null=True)),
                ('second_background_color', fields.IntField(null=True)),
                ('third_background_color', fields.IntField(null=True)),
                ('fourth_background_color', fields.IntField(null=True)),
                ('intensity', fields.IntField(null=True)),
                ('rotation', fields.IntField(null=True)),
                ('emoticon', fields.CharField(null=True, max_length=8)),
            ],
            options={'table': 'wallpapersettings', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('creator', fields.ForeignKeyField('models.User', source_field='creator_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('slug', fields.CharField(unique=True, max_length=64)),
                ('pattern', fields.BooleanField()),
                ('dark', fields.BooleanField()),
                ('document', fields.ForeignKeyField('models.File', source_field='document_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('settings', fields.ForeignKeyField('models.WallpaperSettings', source_field='settings_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'wallpaper', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ChatWallpaper',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', related_name='wallpaper_user', on_delete=OnDelete.CASCADE)),
                ('target', fields.ForeignKeyField('models.User', source_field='target_id', db_constraint=True, to_field='id', related_name='wallpaper_target', on_delete=OnDelete.CASCADE)),
                ('wallpaper', fields.ForeignKeyField('models.Wallpaper', source_field='wallpaper_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('overridden', fields.BooleanField(default=False)),
            ],
            options={'table': 'chatwallpaper', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='InstalledWallpaper',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('wallpaper', fields.ForeignKeyField('models.Wallpaper', source_field='wallpaper_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('settings', fields.ForeignKeyField('models.WallpaperSettings', source_field='settings_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'installedwallpaper', 'app': 'models', 'unique_together': (('user', 'wallpaper'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('theme', fields.ForeignKeyField('models.Theme', source_field='theme_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
                ('base_theme', fields.IntEnumField(description='', enum_type=BaseTheme, generated=False)),
                ('accent_color', fields.IntField()),
                ('outbox_accent_color', fields.IntField(null=True)),
                ('message_colors_animated', fields.BooleanField()),
                ('message_color_1', fields.IntField(null=True)),
                ('message_color_2', fields.IntField(null=True)),
                ('message_color_3', fields.IntField(null=True)),
                ('message_color_4', fields.IntField(null=True)),
                ('wallpaper', fields.ForeignKeyField('models.Wallpaper', source_field='wallpaper_id', db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'themesettings', 'app': 'models', 'unique_together': (('theme', 'base_theme'),), 'pk_attr': 'id'},
            bases=['Model'],
        ),
        ops.CreateModel(
            name='WebAuthorization',
            fields=[
                ('id', fields.BigIntField(generated=True, primary_key=True, unique=True, db_index=True)),
                ('phone_number', fields.CharField(db_index=True, max_length=20)),
                ('password', fields.CharField(default=auth_gen_password, max_length=16)),
                ('random_hash', fields.CharField(default=auth_gen_hash, max_length=32)),
                ('expires_at', fields.BigIntField(default=auth_gen_expires_at)),
                ('user', fields.ForeignKeyField('models.User', source_field='user_id', null=True, db_constraint=True, to_field='id', on_delete=OnDelete.CASCADE)),
            ],
            options={'table': 'webauthorization', 'app': 'models', 'pk_attr': 'id'},
            bases=['Model'],
        ),
    ]
