from .base import BaseDowngrader, BaseUpgrader
from .channel_downgrader import *
from .channel_full_downgrader import *
from .chat_invite_downgrade import *
from .dialog_filter_downgrade import *
from .dialog_filters_downgrade import *
from .invited_users_downgrade import *
from .message_downgrade import *
from .message_fwd_header_downgrade import *
from .message_reply_header_downgrade import *
from .messagemediadocument_downgrade import *
from .peernotifysettings_downgrade import *
from .peersettings_downgrade import *
from .poll_results_downgrade import *
from .user_downgrade import *
from .userfull_downgrade import *

from ..manager import LayerConverter

LayerConverter.register_for_downgrade(UserDowngradeTo136)
LayerConverter.register_for_downgrade(UserDowngradeTo145)
LayerConverter.register_for_downgrade(UserDowngradeTo148)
LayerConverter.register_for_downgrade(UserDowngradeTo160)
LayerConverter.register_for_downgrade(UserDowngradeTo166)
LayerConverter.register_for_downgrade(UserDontDowngrade)

LayerConverter.register_for_downgrade(UserFullDowngradeTo136)
LayerConverter.register_for_downgrade(UserFullDowngradeTo140)
LayerConverter.register_for_downgrade(UserFullDowngradeTo144)
LayerConverter.register_for_downgrade(UserFullDowngradeTo151)
LayerConverter.register_for_downgrade(UserFullDowngradeTo158)
LayerConverter.register_for_downgrade(UserFullDowngradeTo160)
LayerConverter.register_for_downgrade(UserFullDowngradeTo164)
LayerConverter.register_for_downgrade(UserFullDowngradeTo176)
LayerConverter.register_for_downgrade(UserFullDontDowngrade)

LayerConverter.register_for_downgrade(PeerNotifySettingsDowngradeTo136)
LayerConverter.register_for_downgrade(PeerNotifySettingsDowngradeTo140)
LayerConverter.register_for_downgrade(PeerNotifySettingsDontDowngrade)

LayerConverter.register_for_downgrade(PeerSettingsDowngradeTo136)
LayerConverter.register_for_downgrade(PeerSettingsDontDowngrade)

LayerConverter.register_for_downgrade(MessageDowngradeTo136)
LayerConverter.register_for_downgrade(MessageDowngradeTo170)
LayerConverter.register_for_downgrade(MessageDowngradeTo174)
LayerConverter.register_for_downgrade(MessageDowngradeTo176)
LayerConverter.register_for_downgrade(MessageDontDowngrade)

LayerConverter.register_for_downgrade(MessageMediaDocumentDowngradeTo136)
LayerConverter.register_for_downgrade(MessageMediaDocumentDontDowngrade)

LayerConverter.register_for_downgrade(MessageReplyHeaderDowngradeTo136)
LayerConverter.register_for_downgrade(MessageReplyHeaderDowngradeTo166)
LayerConverter.register_for_downgrade(MessageReplyHeaderDontDowngrade)

LayerConverter.register_for_downgrade(MessageFwdHeaderDowngradeTo136)
LayerConverter.register_for_downgrade(MessageFwdHeaderDontDowngrade)

LayerConverter.register_for_downgrade(InvitedUsersDowngradeTo136)
LayerConverter.register_for_downgrade(InvitedUsersDontDowngrade)

LayerConverter.register_for_downgrade(ChatInviteDowngradeTo136)
LayerConverter.register_for_downgrade(ChatInviteDontDowngrade)

LayerConverter.register_for_downgrade(ChannelDowngradeTo136)
LayerConverter.register_for_downgrade(ChannelDowngradeTo148)
LayerConverter.register_for_downgrade(ChannelDowngradeTo164)
LayerConverter.register_for_downgrade(ChannelDowngradeTo166)
LayerConverter.register_for_downgrade(ChannelDowngradeTo167)
LayerConverter.register_for_downgrade(ChannelDontDowngrade)

LayerConverter.register_for_downgrade(ChannelFullDowngradeTo136)
LayerConverter.register_for_downgrade(ChannelFullDowngradeTo140)
LayerConverter.register_for_downgrade(ChannelFullDowngradeTo145)
LayerConverter.register_for_downgrade(ChannelFullDowngradeTo164)
LayerConverter.register_for_downgrade(ChannelFullDowngradeTo168)
LayerConverter.register_for_downgrade(ChannelFullDontDowngrade)

LayerConverter.register_for_downgrade(PollResultsDowngradeTo136)
LayerConverter.register_for_downgrade(PollResultsDontDowngrade)

LayerConverter.register_for_downgrade(DialogFiltersDowngradeTo136)
LayerConverter.register_for_downgrade(DialogFiltersDontDowngrade)

LayerConverter.register_for_downgrade(DialogFilterDowngradeTo136)
LayerConverter.register_for_downgrade(DialogFilterDontDowngrade)
